dist: trusty
language: node_js
node_js: "node"
before_install:
  #!/bin/bash
  - set -e
  - echo "machine github.com" >> ~/.netrc
  - echo "   login tdillon" >> ~/.netrc
  - echo "   password $GH_TOKEN" >> ~/.netrc
script:
  - npm run build
after_success:
  - ls -la
  - git status
#   - git checkout -b gh-pages
#   - rm tsconfig.json .travis.yml package.json .gitignore
#   - git add --all
#   - git commit -m "travis-ci deployment"
#   - git push --force origin gh-pages
branches:
  only:
  - dev