sudo: required
dist: trusty
language: node_js
node_js: "node"
before_install:
  #!/bin/bash
  - set -e
  - echo "machine github.com" >> ~/.netrc
  - echo "   login tdillon" >> ~/.netrc
  - echo "   password $GH_TOKEN" >> ~/.netrc
script:
  - npm run build
after_success:
  - ls -la
  - git checkout -b master
  - rm -rf app/ node_modules/ .gitignore .travis.yml builder.js package.json README.MD system.config.js tsconfig.json
  - git add --all
  - git commit -m "travis-ci deployment"
  - git push --force origin master
branches:
  only:
  - dev